version: "3.9"
services:
  file-server:
    build: .
    image: localhost/go-home-file-server_file-server
    container_name: file-server
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      ROOT_PATH: /app/shared
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASS: ${BASIC_AUTH_PASS}
      LOG_PATH: /app/logs
    volumes:
      - shared_data:/app/shared:Z
      - ./logs/file-server:/app/logs:Z

  reverse-proxy:
    image: docker.io/library/nginx:latest
    container_name: file-server-proxy
    ports:
      - "${PROXY_PORT:-80}:80"
    depends_on:
      - file-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./logs/nginx:/var/log/nginx:Z
      - shared_data:/app/shared:Z

volumes:
  shared_data:
    name: shared_data
    driver: local
